### ISSUE TITLE
BLD: Dropping support for Python 3.8 ?

### ISSUE THREAD

**Issue by neutrinoceros** [neutrinoceros/yt_idefix#203]
There is some motivation to use Python 3.9+ specific features, so I would like to drop support for Python 3.8.
Keeping support for 3.8 is perfectly doable, but I'd like to spare myself the effort if no one is actually relying on it.
I'll give a couple days to interested parties to respond.

ping @xshaokun @dutta-alankar @vdbma

**Comment by xshaokun** [comment]
I'm currently using python 3.8 and I've no problem to upgrade my python version.

However, according to the fast update of the minimum version requirement. I think I should just upgrade my python to 3.11 in case I'll be dropped again next time :)

**Comment by dutta-alankar** [comment]
Still 3.9+ specific features we discussed in the PR ([link here](https://github.com/neutrinoceros/yt_idefix/pull/202#discussion_r1116628048)) has not been implemented. In any case, I have no problem with setting the minimum required version to 3.9.
