### ISSUE TITLE
Call for co-authors to sign the yt-4 paper

### ISSUE THREAD

**Issue by neutrinoceros** [neutrinoceros/yt_idefix#236]
@xshaokun @dutta-alankar and @RitaliG, you've made contributions to this package, and by extension to the yt-project. You are invited to co-sign the paper if you'd like

https://docs.google.com/forms/d/e/1FAIpQLSc8Joz7eEDwLKub2wdTA803tKP1JdpXWWtR-JuSzgjUUZq8Bw/viewform

**Comment by xshaokun** [comment]
Thank you very much for your invitation! May I just enter my information in the form but leave the last two sections alone? Since I skimmed through the paper and I think I‘m not able to make any contribution on the content of the paper at the moment. :(

**Comment by matthewturk** [comment]
Yes, absolutely.

**Comment by dutta-alankar** [comment]
Thanks a lot for the invitation. I have filled up the google form. I'm not sure about the particulars of how I can contribute to the yt4 paper. But I'll be extremely eager to do that in near future.

**Comment by neutrinoceros** [comment]
@dutta-alankar , can you make sure @RitaliG sees this ?

**Comment by RitaliG** [comment]
Hi! Thanks for the invitation. I have also filled up the form. I would be eager to contribute as much I can to the yt-paper.

**Comment by neutrinoceros** [comment]
Awesome, then I'll close this issue as everyone responded :)
