### ISSUE TITLE
DOC: missing documentation for XDMF compat

### ISSUE THREAD

**Issue by neutrinoceros** [neutrinoceros/yt_idefix#239]
documentation was completely overlooked in #209
We should mention that Pluto XDMF files are supported from version 1.1.0 and that `h5py` is required.

**Comment by dutta-alankar** [comment]
Where do I put this documentation?

**Comment by neutrinoceros** [comment]
`README.md` is the documentation ^^

**Comment by dutta-alankar** [comment]
I opened a [PR](https://github.com/neutrinoceros/yt_idefix/pull/241) for this.

**Comment by neutrinoceros** [comment]
closed via #239
