### ISSUE TITLE
Missing documentation of optional parameters passed to `yt.load()`

### ISSUE THREAD

**Issue by dutta-alankar** [neutrinoceros/yt_idefix#247]
`default_species_fields`, `ini_file`, `definitions_header` are optional parameters whose usage is missing in the documentation. Do you think it is a good idea to a few lines about it in README?

**Comment by neutrinoceros** [comment]
Yes, absolutely.

**Comment by dutta-alankar** [comment]
@neutrinoceros Can you tell me how to access these configurations and change the default in `yt.load`? I'll then open a PR adding these changes in the documentation.

**Comment by neutrinoceros** [comment]
(I encourage you to take a look at `yt.load's` source code if you're curious. It's probably simpler than you'd expect)

**Comment by dutta-alankar** [comment]
> Basically, the idea is that `yt.load` accepts arbitrary arguments (both positional and keyword), and will pass them down to the selected `Dataset` subclass' `__init__` method. This means custom arguments are added to `yt.load` in these methods. Additionally, note that most arguments in, say `GoodBoyDataset.__init__`, are actually just mirroring `Dataset.__init__`'s signature.
> 
> Does this answer your question ?

@neutrinoceros Yes thanks. This was helpful. I'll also look up `yt.load` and update the docs.
