### ISSUE TITLE
Merge the field class of Pluto-vtk and Pluto-xdmf

### ISSUE THREAD

**Issue by xshaokun** [neutrinoceros/yt_idefix#253]
Here I would like to discuss the feasibility of using a common field class for both Pluto-vtk and Pluto-xdmf.

So far, Pluto-vtk and Idefix-vtk share a common vtk field class. To do this, the upper case is applied to Pluto-vtk's field name.

However, I guess the field names should be more common for Pluto-vtk and Pluto-xdmf, and the field class should be _classified by code instead of output format_. By doing this, maybe we can drop the upper case operation on Pluto-vtk's field name and it would be easier to maintain the field class.

Actually, I started using Pluto in version 4.4, so I don't know about the field name in the version before that. What about your opinion? @neutrinoceros @dutta-alankar

**Comment by neutrinoceros** [comment]
That's sounds like a good idea. We went for a quicker solution with @vdbma yesterday in #251, but long term, separating field classes seems more maintainable indeed.

So far it's not been clear to me exactly which versions of Pluto this frontend actually supports. I guess if you've not used older versions than 4.4 it means that all of our test datasets are from this version, and we cannot claim compatibility with older ones. In practice, I'm willing to support versions as old as needed as long as it doesn't break existing compatibility, but I wouldn't worry about it too much. We can always adjust to novel needs if anyone complains loud enough :)

**Comment by dutta-alankar** [comment]
I have worked with PLUTO 4.2 and higher. I haven't seen any change in the fields. The recent version of PLUTO also supports particles. I was wondering if its visualization can be included in yt.

**Comment by neutrinoceros** [comment]
> The recent version of PLUTO also supports particles. I was wondering if its visualization can be included in yt

there are a couple important limitations:
- I don't know how to combine particles with grid-based data into a single yt dataset. Surely this is doable, but we need someone to champion that, or guide us, in yt_idefix
- yt currently only supports particle sets with Cartesian coordinate systems. This limitation can and should be lifted, but that's very likely a substantial effort.

That said, I would be happy to provide any help I can with this.

**Comment by xshaokun** [comment]
> I have worked with PLUTO 4.2 and higher. I haven't seen any change in the fields.

I checked the `CHANGES` log of Pluto and see the following change under section `CHANGES from 4.2`:

> - Magnetic field variable names have been changed 
  from "bx1", "bx2", "bx3" to "Bx1", "Bx2", "Bx3"

It seems like the magnetic field variable names are different in v4.2. Do you still have the code of Pluto v4.2 and help me check that? @dutta-alankar 

If the output variable names are different, our Pluto-xdmf can only support Pluto 4.3 or higher.

**Comment by neutrinoceros** [comment]
Additional thoughts: Field classes are reused purely for practical reasons. If any difference arise between, say Idefix and Pluto vtks formats, that justify splitting Field classes, I'm all for it, though it is not clear if we should *merge* existing classes, unless it brings functionality from one to the other ?

**Comment by xshaokun** [comment]
> If any difference arise between, say Idefix and Pluto vtks formats, that justify splitting Field classes, I'm all for it, though it is not clear if we should _merge_ existing classes, unless it brings functionality from one to the other ?

If variable names are the only difference between field classes, I think there is no difference between the fields (names) of Pluto-vtk and Pluto-xdmf. Because they share the same set of variable names in Pluto, that's why I propose they should be merged. 

Namely, the current `PlutoXdmfFields` is enough for Pluto-vtk output and we don't need `PlutoVtkFields` anymore. The schematic diagram is as follows: 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/22034707/233567042-493939ce-3a4f-4cef-bbc5-974bdfcb2ab2.png">

**Comment by neutrinoceros** [comment]
That graph makes sense to me, let's do this !

**Comment by xshaokun** [comment]
We could continue our discussion of #255 here until figure out a conclusion :)

**Comment by neutrinoceros** [comment]
Okay. So if we normalise builtin field names to upper case we'll be consistent with how fields are referred to in Pluto and Idefix's respective source codes. I think this is the best way forward. However, I do want to preserve case flexibility for user-defined fields, which was the motivation for #251, so we should only normalise known names like `"rho"`, "vx1", "bx1" and the likes

**Comment by xshaokun** [comment]
> However, I do want to preserve case flexibility for user-defined fields, which was the motivation for #251, so we should only normalise known names like `"rho"`, "vx1", "bx1" and the likes

It makes sense to me. As you mentioned that, I'm also considering whether to remove those user-defined fields in `PlutoXdmfFields()` or not. https://github.com/neutrinoceros/yt_idefix/blob/dd6c35291e84bb7887c5e464197cb792835e721a/yt_idefix/fields.py#L99-L133

Those field names , e.g. `Temp`, are defined arbitrarily, and I use `tmp` instead. Since there is no convention on that, such implement may not be useful for all users.

**Comment by neutrinoceros** [comment]
Oh I did not understand that these names were arbitrary. User-specific fields do not belong in a frontend so I'm afraid they have to go indeed

**Comment by xshaokun** [comment]
Well, now I would like to double-check the plan:

1. Reorganize the field classes following the graph above
2. Normalize the builtin field names in upper case 
4. Cleanup `PlutoFields`: remove user-specific fields, and rename the alias ( currently they are not all in standard as you said (yt-names or pluto-names)
5. Make the tests all green.

**Comment by neutrinoceros** [comment]
approved
