### ISSUE TITLE
BUG: The value of derived fields cannot update correctly

### ISSUE THREAD

**Issue by xshaokun** [neutrinoceros/yt_idefix#67]
Here is a simple piece of code for reproducing the bug quickly.

```Python
import yt
import yt_idefix

from yt.utilities.physical_constants import mh, kb

sedov = "pluto_sedov/data.0018.vtk"
ds = yt_idefix.load(sedov, unit_system="cgs")

def temp(field, data):
    mu = 0.6
    return mu * mh * data[("gas","pressure")] / data[("gas","density")] / kb
ds.add_field(name=("gas","temperature"),function=temp, units="K",sampling_type="local")

ad = ds.all_data()
print("added_temperature = ", ad["gas","temperature"])
```

The result showed that the value of temperature is infinity or other wrong number, due to the wrong value of [density]. Using `("idefix-vtk","RHO)` and `("idefix-vtk","PRS)` doesn't make differences. I also tried different ways to add the derived_field, e.g. `@yt.derived_field`

```bash
yt : [INFO     ] 2022-01-15 16:50:59,762 Parameters: current_time              = 0.02279213 code_time
yt : [INFO     ] 2022-01-15 16:50:59,763 Parameters: domain_dimensions         = [48 48 48]
yt : [INFO     ] 2022-01-15 16:50:59,763 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2022-01-15 16:50:59,764 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2022-01-15 16:50:59,764 Parameters: cosmological_simulation   = 0
/share/shaokun/Apps/anaconda3/lib/python3.7/site-packages/unyt/array.py:1779: RuntimeWarning: divide by zero encountered in true_divide
  inp0.view(np.ndarray), inp1.view(np.ndarray), out=out_func, **kwargs
added_temperature =  [-2.54617343e-45  4.49557643e-49 -1.48152055e-97 ...             inf
             inf             inf] K
```

I found that calling [density] field before [temperature] would make [temperature] right, such as `print(ad["gas","density"].

I made the same test for FLASH data (by force-overriding the original temperature function) and it works. So I think the bug might come from this extension instead of yt, or might not.

In my understanding, the information of derived fields are stored in `FieldInfoContainer` after adding them, with their dependent field arrays whose value were generated randomly and only update once they are called. So the bug seems like that the initial array was used when calculating the derived field. I tried to figure out when the array was updated but failed.

**Comment by neutrinoceros** [comment]
This is extremely puzzling to me, though I don't think I've exercised custom fields yet with this extension so, while I'm not certain the problem is in `yt_idefix` itself yet, it seems plausible.

I've tried switching to `sampling_type="cell"` but the result is exactly the same (I get `inf` everywhere)

What's really intriguing is that performing the same operation directly on the data object yields sane results

```
In [1]: (ad["gas", "pressure"] / ad["gas", "density"] * mh / kb * 0.6).to("K")
Out[1]:
unyt_array([6.23539075e+03, 6.31252636e+03, 6.48937715e+03, ...,
            7.27368980e-04, 7.27368980e-04, 7.27368980e-04], 'K')
```

**Comment by xshaokun** [comment]
> What's really intriguing is that performing the same operation directly on the data object yields sane results.

Yes. I also tried this before. It looks like the value of field stored in data is wrong until such field is called from `ad`, the object return by `ds.all_data()`. The mechanism behind that is hard for me to figure out.

**Comment by neutrinoceros** [comment]
Yes this part of yt is kinda obfuscated. I'll have a look, and try to understand how this frontend is any different from others. In particular I'll look at the AMRVAC frontend that I co-authored.

**Comment by neutrinoceros** [comment]
So I suspect (but that's just a hunch) that the indexing of the grid is wrong somehow, which might explain that the `data` chunk in the custom field function doesn't behave like an "all_data" `YTRegion`. An important specificity of the Pluto/Idefix data vtk format is that fields are written in a single contiguous block (unigrid). This kind o grid is supported  by other mainline frontends such as `nc4_cm1` and `open_pmd`.

I note that defining simpler custom fields as
```python
return data[("gas","pressure")]
```
or
```python
return data[("gas","density")]
```
works. While
```python
return  data[("gas","pressure")] / data[("gas","density")]
```
doens't (returns all inf). So I'm not even sure about my interpretation above.

**Comment by xshaokun** [comment]
> which might explain that the `data` chunk in the custom field function doesn't behave like an "all_data" `YTRegion`.

I tracked the type of `data` chunk by
```Python
print("data = ", type(data), "density = ", data[("gas","density")].max())
return data[("gas","pressure")] / data[("gas","density")]
```
its type is first `FieldDetector` and `YTRegion` later, behaving the same as in other frontends, but the value is wrong `nan`
```python
data =  <class 'yt.fields.field_detector.FieldDetector'> density =  1.0000999766020406 code_mass/code_length**3
data =  <class 'yt.data_objects.selection_objects.region.YTRegion'> density =  nan g/cm**3
data =  <class 'yt.data_objects.selection_objects.region.YTRegion'> density =  nan g/cm**3
data =  <class 'yt.data_objects.selection_objects.region.YTRegion'> density =  nan g/cm**3
```

**Comment by xshaokun** [comment]
> So I suspect (but that's just a hunch) that the indexing of the grid is wrong somehow

You're right! It's caused by index.

I found the field array is initialized by `IdefixIOHandler._read_fluid_selection` method, so I thought that's where the bug is. Therefore, I tried to modify that part referring to AMRVAC frontend and it works now! I'll create a PR to fix this bug :)

**Comment by neutrinoceros** [comment]
Awesome ! Thank you very much
