### ISSUE TITLE
TODO: parse units and input parameters in unit definitions (Pluto)

### ISSUE THREAD

**Issue by xshaokun** [neutrinoceros/yt_idefix#83]
For the part of parsing units, I considered the case where defined constants are used to define units. However when I reviewed the test problems provided by PLUTO, I found units can be defined in such way:

``` 
#define  UNIT_LENGTH                    (5.2*CONST_au)
#define  UNIT_DENSITY                   (CONST_Msun/(UNIT_LENGTH*UNIT_LENGTH*UNIT_LENGTH))
#define  UNIT_VELOCITY                  (sqrt(CONST_G*g_inputParam[Mstar]*CONST_Msun/UNIT_LENGTH)/(2.*CONST_PI))
```

where involves units defined previously and input parameters. So the implementation of parsing units should be improved or refactored in the future so that it can handle such definition.

**Comment by neutrinoceros** [comment]
Thanks for reporting this ! For closure, any one else who would like to give this a try is welcome to.
(https://www.redhat.com/en/blog/dont-lick-cookie ;) )

**Comment by neutrinoceros** [comment]
@xshaokun are you still interested in doing this ?
I'm thinking about opening a PR to merge yt_idefix into mainline yt, so I'd rather have any important change happen here first if possible.

**Comment by xshaokun** [comment]
> @xshaokun are you still interested in doing this ?

Oh yes. I'm glad to know that this package will be merged into yt. 

I'll try to propose a solution for this issue in the following week.

**Comment by neutrinoceros** [comment]
Thank for your quick reply. For the record, merging this into yt is still on the time scale of a couple month, so I mean no rush !
