### ISSUE TITLE
BUG: endianness isn't parsed (Pluto vtk)

### ISSUE THREAD

**Issue by neutrinoceros** [neutrinoceros/yt_idefix#85]
We may have a bug to fix for the case big-endians are used. Idefix _always_ outputs in little endian so it's currently hard-coded in the frontend.

_Originally posted by @neutrinoceros in https://github.com/neutrinoceros/yt_idefix/pull/84#discussion_r797910881_

**Comment by xshaokun** [comment]
Here is the description on vtk output in PLUTO:

>   VTK file are written following big endian order. 
>   Therefore, we swap endianity only if local architecture has little 
>   endian ordering. 

So it should be little-endians for all x86 platforms. But we still need to cover the case for big-endians.

**Comment by xshaokun** [comment]
Ah I noticed one thing that confused me. In vtk_io.py, all the datatypes specified for `np.fromfile` are `'>f'`. The `>` means big-endians, doesn't it?  Sorry, I'm not familiar with reading binary data.

**Comment by neutrinoceros** [comment]
You are absolutely right, I wrote this comment/issue off the top of my head without checking the actual code, and I mis-remembered it. Idefix vtk are indeed always *BIG* endian, and we don't swap bytes anywhere that I know of.

Now I'm wondering why it works at all with your little-endian datasets !

**Comment by xshaokun** [comment]
That's really weird. I think I should spend some time to dip into the io part of PLUTO. Seems like it wrote data in big-endian but record it as liitle.

**Comment by neutrinoceros** [comment]
From PLUTO 4.4 User Guide 

> Single or multiple VTK files can be written by specifying either single file or multiple files in your pluto.ini and data values are always written using single precision with byte order set to big endian.

So I think there is nothing to worry about after all, Pluto and Idefix actually behave the same (which isn't too surprising). I think we got confused because endianity of the machine is recorded, but it actually doesn't matter at read time, it's really just something Pluto takes care of for us.

I think I can just close this. Thanks a lot for getting involved in the discussion, it really helps !
