### ISSUE TITLE
BUG: phi-slices in spherical geometries are glitchy

### ISSUE THREAD

**Issue by neutrinoceros** [neutrinoceros/yt_idefix#86]
In this example, results are correct (or at least expected) with normal = "r" and normal = "theta", but the poloidal slice (normal = "phi") is full of glitches

```python
import yt
import yt_idefix

ds = yt.load("tests/data/pluto_disk_planet/data.0010.vtk")
for normal in ("r", "theta", "phi"):
    p = yt.SlicePlot(ds, normal, "density")
    p.save("/tmp/", mpl_kwargs=dict(bbox_inches="tight"))
```

![data 0010 vtk_Slice_r_density](https://user-images.githubusercontent.com/14075922/152244605-90749060-fba6-4213-88cf-a35edcd7cf3d.png)
![data 0010 vtk_Slice_theta_density](https://user-images.githubusercontent.com/14075922/152244607-c3fbce4b-2875-4912-861b-cf3eb8d68194.png)

![data 0010 vtk_Slice_phi_density](https://user-images.githubusercontent.com/14075922/152244600-6ad89ae8-92c1-41df-ab50-9375a8e95706.png)

I note that this is currently our only spherical vtk dataset. A similar script using a spherical dataset with Idefix's dump format yields expected results
![dump 0015 dmp_Slice_phi_density](https://user-images.githubusercontent.com/14075922/152245791-b0c3a0dd-b413-4668-bab9-40fea6b7f46d.png)

I think it's possibly a bug in yt itself, but I've never seen it with any other frontend so I'll inspect a bit further before I report upstream.

**Comment by neutrinoceros** [comment]
this may be a bug in the pixelizer that appears only at low resolutions (here we only have 16 cells in the latitudinal direction)

**Comment by xshaokun** [comment]
> I note that this is currently our only spherical vtk dataset.

Just remind, there's another spherical vtk dataset for idefix `tests/data/FargoMHDSpherical/data.0010.vtk"`, and it seems normal with 64 cells in the latitudinal direction

![data 0010 vtk_Slice_phi_density](https://user-images.githubusercontent.com/22034707/152280127-02758f62-085b-41c7-9e36-97ffeb579fd8.png)

Therefore, I increased the resolution of theta direction to 64 cells for pluto_disk_planet, but it's glitchy too. It seems that low resolution is not the main reason.
![data 0001 vtk_Slice_phi_density](https://user-images.githubusercontent.com/22034707/152281988-cfdb02d6-b6a2-42e2-b8b7-4a48dda68f5e.png)

**Comment by neutrinoceros** [comment]
Great ! Then that is almost certainly an actual frontend bug.

**Comment by neutrinoceros** [comment]
Okay this is almost definitely a bug in yt itself.

Running with yt 4.0.1 and yt_idefix 0.10
```python
import yt
import yt_idefix

ds = yt.idefix_load("tests/data/pluto_disk_planet/data.0010.vtk")
p = yt.SlicePlot(ds, "phi", "density")
p.save("/tmp/", mpl_kwargs=dict(bbox_inches="tight"))
```
I get
![data 0010 vtk_Slice_phi_density](https://user-images.githubusercontent.com/14075922/152348963-bf4c1863-4bed-44bf-a7c4-d2e4426cbdf0.png)

so there are a number of issues in this image that are fixed in yt 4.0.2 _but_ the pixelizer is apparently broken now. This is almost certainly on me since I wrote most of the patches for yt 4.0.2

I'll check to see if this image is reproducible with yt-4.0.1 and a modified version of yt_idefix 11.0 that accept yt 4.0.1

**Comment by neutrinoceros** [comment]
indeed, can reproduce this exact image using the old yt_idefix.load function, so this is def' a regression in yt 4.0.2 :(
I'll update yt_idefix to allow yt 4.0.1 again, and I'll try to fix this in yt itself later (it's a bit complicated to patch this up right now before the release is officially announced)

**Comment by neutrinoceros** [comment]
Still scratching my head over this before I report it upstream but I haven't found _any_ other dataset where this bug shows up. A potentially key difference here is that the simulation box has a minimal latitude of precisely 0.

**Comment by neutrinoceros** [comment]
Fixed upstream with https://github.com/yt-project/yt/pull/3782
![data 0010 vtk_Slice_phi_density](https://user-images.githubusercontent.com/14075922/152703572-b230eea2-13db-483e-a521-096d4664592e.png)
